title: "Canada DevOps Community of Practice"
description: "Canada's DevOps & GenAI Community, Hackathons, Open Source, Events"
url: "https://canadadevopscommunityofpracticehackathonseries.io"
baseurl: ""
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
collections:
  pages:
    output: true
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      sidebar:
        nav: "main"
