title: "Canada DevOps Community of Practice"
description: "Empowering DevOps practitioners in Canada through collaboration and innovation."
remote_theme: "mmistakes/minimal-mistakes@latest"
plugins:
  - jekyll-remote-theme
