title: "Canada DevOps Community of Practice"
email: info@canadadevops.org
description: "Empowering DevOps practitioners in Canada through collaboration and innovation."
baseurl: "/CanadaDevOpsCommuntiyOfPractice.io"
url: "https://canadadevopscommunity2025.github.io"
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

# Navigation
navigation:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/
  - title: "Events"
    url: /events/
  - title: "Community"
    url: /community/
  - title: "Sponsors"
    url: /sponsors/
  - title: "Contact"
    url: /contact/
  - title: "Join"
    url: /join/

logo: "/assets/logo.png" # Place your logo here
minimal_mistakes_skin: "air"
