title: "Canada DevOps Community of Practice"
email: info@canadadevops.org
description: "Empowering DevOps practitioners in Canada through collaboration and innovation."
baseurl: "" # leave blank for user/organization site
url: "https://canadadevopscommunity2025.github.io/CanadaDevOpsCommuntiyOfPractice.io"
remote_theme: "mmistakes/minimal-mistakes@gh-pages"

plugins:
  - jekyll-remote-theme

# Navigation
navigation:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/
  - title: "Events"
    url: /events/
  - title: "Community"
    url: /community/
  - title: "Sponsors"
    url: /sponsors/
  - title: "Contact"
    url: /contact/
  - title: "Join"
    url: /join/

# Minimal Mistakes settings
logo: "/assets/logo.png"
minimal_mistakes_skin: "default"
atom_feed:
  path: "/feed.xml"
