# --- Site basics ---
title: "Canada DevOps Community of Practice"
email: info@canadadevops.org
description: "Empowering DevOps practitioners in Canada through collaboration and innovation."
url: "https://canadadevopscommunity2025.github.io"     # no trailing slash
baseurl: "/CanadaDevOpsCommuntiyOfPractice.io"         # must match repo name exactly

# --- Theme ---
remote_theme: "mmistakes/minimal-mistakes@4.27.3"      # pin a working release
minimal_mistakes_skin: "aqua"                            # color scheme

# --- Plugins (only what GH Pages supports) ---
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

# --- Permalinks & Markdown niceties (optional but recommended) ---
permalink: /:categories/:title/
markdown: kramdown

# --- Collections to support /_pages folder (optional, tidy) ---
collections:
  pages:
    output: true
    permalink: /:name/

# --- Defaults: apply layout + sidebar nav to pages ---
defaults:
  - scope:
      path: ""           # all files
      type: pages
    values:
      layout: single
      sidebar:
        nav: "main"      # will refer to _data/navigation.yml → main:

# --- Masthead logo (works with Minimal Mistakes) ---
logo: "/assets/logo.png"

# --- Footer/social (fill when ready) ---
author:
  name: "Canada DevOps CoP"
